credentials:
  username: ''
  id: ''
  secret: ''
  scope: 'user-read-private user-read-playback-state user-modify-playback-state'
  uri: 'http://127.0.0.1:443'

# assumes display is square
dimensions:
  width: 720

fonts:
  font_family: 'Quicksand'
  track: 20
  artist: 20
  release_date: 20

timings:
  poll_interval: 5
  poll_interval_sleep: 25

palette:
  count: 8
  track_offset: 0
  artist_offset: 2
  release_date_offset: 3