credentials:
  username: ''
  id: ''
  secret: ''
  scope: 'user-read-private user-read-playback-state user-modify-playback-state'
  uri: ''

# assumes display is either horizontal or square
dimensions:
# dell
#  display_width: 2560
#  display_height: 1440

# mac book
  display_width: 1010
  display_height: 1010

# raspberry pi
#  display_width: 365
#  display_height: 365

fonts:
  font_family: 'Courier New'
  track: 14
  artist: 14
  release_date: 13

colors:
  track_light: '#ede3d3'
  track_dark: '#45413b'
  artist_light: '#f7bb43'
  artist_dark: '#9e6a03'
  background: 'black'

poll_interval: 5
poll_interval_sleep: 25
