credentials:
  username: ''
  id: ''
  secret: ''
  scope: 'user-read-private user-read-playback-state user-modify-playback-state'
  uri: 'http://127.0.0.1:443'

# assumes display is square
dimensions:
  width: 720

fonts:
  font_family: 'Quicksand'
  track: 22
  artist: 22
  release_date: 22

colors:
  track_light: '#dac5a4'
  track_dark: '#45413b'
  artist_light: '#dc9609'
  artist_dark: '#9e6a03'
  background: 'black'

poll_interval: 5
poll_interval_sleep: 25
