credentials:
  username: ''
  id: ''
  secret: ''
  scope: 'user-read-private user-read-playback-state user-modify-playback-state'
  uri: ''

# assumes display is either horizontal or square
dimensions:
# dell
#  display_width: 2560
#  display_height: 1440

# mac book
  display_width: 1680
  display_height: 1050

# raspberry pi
#  display_width: 640
#  display_height: 640

fonts:
  font_family: 'Courier New'
  track: 13
  artist: 13

colors:
  track: '#b3ab9f'
  artist: '#f2af29'
  background: 'black'
#  background: '#3b3b3b'

poll_interval: 5
poll_interval_sleep: 25
